/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BD;

import GUI.Q1Dificil;
import GUI.Q1Facil;
import GUI.Q1Medio;
import GUI.Q2Facil;
import GUI.Q2Medio;
import GUI.Q2Dificil;
import GUI.Q3Dificil;
import GUI.Q3Facil;
import GUI.Q3Medio;
import GUI.Q4Dificil;
import GUI.Q4Facil;
import GUI.Q4Medio;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rec17
 */
public class VentanaPuntajes extends javax.swing.JFrame {
    ConexionBD con= new ConexionBD();
    Connection cn = con.conexion();
    public static boolean facil,medio,dificil,quimuno,quimdos,quimtres,quimcuatro;
    public static String dificultadparaBD,juegoparaBD; 
    /**
     * Creates new form NewJFrame
     */
    public VentanaPuntajes() {
        initComponents();
        JLBPuntaje.setEnabled(false);
        this.setLocationRelativeTo(null);
        setTitle("Ventana de puntajes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        JTFNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        JBTPuntaje = new javax.swing.JButton();
        JLBPuntaje = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JLBMemJugado = new javax.swing.JLabel();
        JLBDifJugado = new javax.swing.JLabel();
        JLBFechaJugado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        JTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFNombreKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Puntaje:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Ventana de Puntajes");

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enviar(evt);
            }
        });

        JBTPuntaje.setText("Obtener Puntaje y Datos");
        JBTPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObtenerPuntaje(evt);
            }
        });

        JLBPuntaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLBPuntaje.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Memorama Jugado");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Dificultad Jugada:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Fecha de juego:");

        JLBMemJugado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JLBDifJugado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        JLBFechaJugado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLBFechaJugado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLBDifJugado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JLBPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(JBTPuntaje))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLBMemJugado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(JTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel3)
                                                    .addComponent(JLBPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(JBTPuntaje)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addComponent(JLBMemJugado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(JLBDifJugado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(JLBFechaJugado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void EstablecerPuntajePorDefault(){
        if(quimuno==true){
            juegoparaBD="Quimica Inorganica 1";
            
            if(facil==true){
            Q1Facil llamaraclaseQ1F=new Q1Facil();
            dificultadparaBD="Facil";
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ1F.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }
            if(medio==true){
            Q1Medio llamaraclaseQ1M=new Q1Medio();
            dificultadparaBD="Medio";
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ1M.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }
            if(dificil==true){
            dificultadparaBD="Dificil";
            Q1Dificil llamaraclaseQ1D=new Q1Dificil();
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ1D.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }
        }
        if(quimdos==true){
            juegoparaBD="Quimica Organica 2";
            if(facil==true){
            dificultadparaBD="Facil";
            Q2Facil llamaraclaseQ2F=new Q2Facil();
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ2F.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }
            if(medio==true){
            dificultadparaBD="Medio";
            Q2Medio llamaraclaseQ2M=new Q2Medio();
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ2M.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }
            if(dificil==true){
            dificultadparaBD="Dificil";
            Q2Dificil llamaraclaseQ2D=new Q2Dificil();
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ2D.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }
        }
        if(quimtres==true){
            juegoparaBD="Quimica Avanzada 3";
            if(facil==true){
            dificultadparaBD="Facil";
            Q3Facil llamaraclaseQ3F=new Q3Facil();
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ3F.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }
            if(medio==true){
            dificultadparaBD="Medio";
            Q3Medio llamaraclaseQ3M=new Q3Medio();
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ3M.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }
            if(dificil==true){
            dificultadparaBD="Dificil";
            Q3Dificil llamaraclaseQ3D=new Q3Dificil();
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ3D.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }
        }
        if(quimcuatro==true){
            juegoparaBD="Quimica Termoquimica 4";
            if(facil==true){
            dificultadparaBD="Facil";
            Q4Facil llamaraclaseQ4F=new Q4Facil();
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ4F.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }
            if(medio==true){
            dificultadparaBD="Medio";
            Q4Medio llamaraclaseQ4M=new Q4Medio();
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ4M.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }
            if(dificil==true){
            dificultadparaBD="Dificil";
            Q4Dificil llamaraclaseQ4D=new Q4Dificil();
            JLBPuntaje.setText(String.valueOf(llamaraclaseQ4D.puntaje));
            JBTPuntaje.setEnabled(false);
            JLBMemJugado.setText(juegoparaBD);
            JLBDifJugado.setText(dificultadparaBD);
            }   
        }
    }
    private void Enviar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enviar
        try {
            if(((JLBPuntaje.getText().length())==0)&&((JTFNombre.getText().length())==0)){
                JOptionPane.showMessageDialog(rootPane, "Debes Ingresar un nombre", "Puntaje", HEIGHT);
                JOptionPane.showMessageDialog(rootPane, "Debes obtener tu puntaje", "Puntaje", HEIGHT);
            }
            if((JTFNombre.getText().length())!=0 ){
            PreparedStatement pps= (PreparedStatement) cn.prepareStatement("INSERT INTO jugador(Nombre_Del_Jugador,Puntaje) VALUES(?,?)");
            pps.setString(1, JTFNombre.getText());
            pps.setString(2, String.valueOf(JLBPuntaje.getText()));
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Puntaje Guardado");
            }
            else if((JTFNombre.getText().length())==0){
                JOptionPane.showMessageDialog(rootPane, "Introduce un nombre");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPuntajes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Enviar

    private void ObtenerPuntaje(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObtenerPuntaje
        EstablecerPuntajePorDefault();
    }//GEN-LAST:event_ObtenerPuntaje

    private void JTFNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNombreKeyTyped
              if(JTFNombre.getText().length()>=15){
        evt.consume();
        JOptionPane.showMessageDialog(rootPane, "Tu nombre no debe tener mas de 15 caracteres de longitud");
    }
    }//GEN-LAST:event_JTFNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPuntajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPuntajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTPuntaje;
    private javax.swing.JLabel JLBDifJugado;
    private javax.swing.JLabel JLBFechaJugado;
    private javax.swing.JLabel JLBMemJugado;
    private javax.swing.JLabel JLBPuntaje;
    private javax.swing.JTextField JTFNombre;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
